export enum AdminRoutes {
  ProjectsList = '/projects',
  ProjectsItem = '/projects/:projectId',
  BranchesList = '/branches',
  BranchesItem = '/branches/:branchId',
  EndpointsList = '/endpoints',
  EndpointsItem = '/endpoints/:endpointId',
  UsersList = '/users',
  UsersItem = '/users/:userId',
  PageserversList = '/pageservers',
  PageserversItem = '/pageservers/:pageserverId',
  SafekeepersList = '/safekeepers',
  SafekeepersItem = '/safekeepers/:safekeeperId',
  PlatformsList = '/platforms',
  OperationsList = '/operations',
  OperationsItem = '/operations/:operationId',
  InvitesList = '/invites',
  ConsoleSettings = '/settings',
}
