import React from 'react';
import { ConsoleRoutes } from '../../routes/routes';
import { IconName } from '../../components/SvgIcon/SvgIcon';
import { ProjectItemBreadcrumbLabel } from '../../components/BreadcrumbsLabels/ProjectItemBreadcrumbLabel';
import { BranchItemBreadcrumbLabel } from '../../components/BreadcrumbsLabels/BranchItemBreadcrumbsLabel';

export const ROUTES_NAMES: Record<ConsoleRoutes, React.ReactNode> = {
  [ConsoleRoutes.Root]: 'Neon',
  [ConsoleRoutes.Home]: 'Management console',
  [ConsoleRoutes.ProjectsList]: 'Projects',
  [ConsoleRoutes.ProjectsItem]: 'Dashboard',
  [ConsoleRoutes.ProjectsItemQuery]: 'SQL Editor',
  [ConsoleRoutes.ProjectsItemInsigts]: 'Insights',
  [ConsoleRoutes.ProjectsItemTables]: 'Tables',
  [ConsoleRoutes.ProjectsItemSettings]: 'Settings',
  [ConsoleRoutes.ProjectsItemSettingsGeneral]: 'General settings',
  [ConsoleRoutes.ProjectsItemSettingsOperations]: 'Operations',
  [ConsoleRoutes.ProjectsItemSettingsDatabases]: 'Databases',
  [ConsoleRoutes.ProjectsItemDatabases]: 'Databases',
  [ConsoleRoutes.ProjectsItemRoles]: 'Roles',
  [ConsoleRoutes.ProjectsItemIntegrations]: 'Integrations',
  [ConsoleRoutes.ProjectsItemOperations]: 'Operations',
  [ConsoleRoutes.UserBilling]: 'Billing',
  [ConsoleRoutes.UserSettings]: 'User settings',
  [ConsoleRoutes.UserSettingsApiKeys]: 'API Keys',
  [ConsoleRoutes.UserSettingsAccount]: 'Account',
  [ConsoleRoutes.ProjectsItemBranches]: 'Branches',
  [ConsoleRoutes.ProjectsItemBranchesNew]: 'New branch',
  [ConsoleRoutes.ProjectsItemBranchesItem]: 'Branch',
  [ConsoleRoutes.ProjectsItemBranchesItemEndpointsNew]: 'New Endpoint',
  [ConsoleRoutes.ProjectsItemEndpoints]: 'Endpoints',
  [ConsoleRoutes.ProjectsItemEndpointsNew]: 'New endpoint',
  [ConsoleRoutes.ProjectsItemEndpointsItem]: 'Endpoint item',
  [ConsoleRoutes.ProjectsItemEndpointsItemEdit]: 'Edit endpoint',
};

export const ROUTES_BREADCRUMBS_LABELS: Record<ConsoleRoutes, React.ReactNode> = {
  [ConsoleRoutes.Root]: 'Home',
  [ConsoleRoutes.Home]: '',
  [ConsoleRoutes.ProjectsList]: '',
  [ConsoleRoutes.ProjectsItem]: <ProjectItemBreadcrumbLabel />,
  [ConsoleRoutes.ProjectsItemQuery]: 'SQL Editor',
  [ConsoleRoutes.ProjectsItemInsigts]: 'Insights',
  [ConsoleRoutes.ProjectsItemTables]: 'Tables',
  [ConsoleRoutes.ProjectsItemSettings]: 'Settings',
  [ConsoleRoutes.ProjectsItemSettingsGeneral]: '',
  [ConsoleRoutes.ProjectsItemSettingsOperations]: '',
  [ConsoleRoutes.ProjectsItemSettingsDatabases]: '',
  [ConsoleRoutes.ProjectsItemDatabases]: 'Databases',
  [ConsoleRoutes.ProjectsItemRoles]: 'Roles',
  [ConsoleRoutes.ProjectsItemIntegrations]: 'Integrations',
  [ConsoleRoutes.ProjectsItemOperations]: 'Operations',
  [ConsoleRoutes.UserBilling]: 'Billing',
  [ConsoleRoutes.UserSettings]: '',
  [ConsoleRoutes.UserSettingsApiKeys]: 'API Keys',
  [ConsoleRoutes.UserSettingsAccount]: 'Account',
  [ConsoleRoutes.ProjectsItemBranches]: 'Branches',
  [ConsoleRoutes.ProjectsItemBranchesNew]: 'New branch',
  [ConsoleRoutes.ProjectsItemBranchesItem]: <BranchItemBreadcrumbLabel />,
  [ConsoleRoutes.ProjectsItemBranchesItemEndpointsNew]: 'New Endpoint',
  [ConsoleRoutes.ProjectsItemEndpoints]: 'Endpoints',
  [ConsoleRoutes.ProjectsItemEndpointsNew]: 'New endpoint',
  [ConsoleRoutes.ProjectsItemEndpointsItem]: 'Endpoint item',
  [ConsoleRoutes.ProjectsItemEndpointsItemEdit]: 'Edit endpoint',
};

export const ROUTES_ICONS: Record<ConsoleRoutes, IconName> = {
  [ConsoleRoutes.Root]: 'project_20',
  [ConsoleRoutes.Home]: 'project_20',
  [ConsoleRoutes.ProjectsList]: 'project_20',
  [ConsoleRoutes.ProjectsItem]: 'overview_20',
  [ConsoleRoutes.ProjectsItemQuery]: 'editor_20',
  [ConsoleRoutes.ProjectsItemInsigts]: 'graph_20',
  [ConsoleRoutes.ProjectsItemTables]: 'table_20',
  [ConsoleRoutes.ProjectsItemSettings]: 'settings_20',
  [ConsoleRoutes.ProjectsItemSettingsGeneral]: 'settings_20',
  [ConsoleRoutes.ProjectsItemSettingsOperations]: 'operations_20',
  [ConsoleRoutes.ProjectsItemSettingsDatabases]: 'database_20',
  [ConsoleRoutes.ProjectsItemDatabases]: 'database_20',
  [ConsoleRoutes.ProjectsItemRoles]: 'roles_20',
  [ConsoleRoutes.ProjectsItemIntegrations]: 'integrations_16',
  [ConsoleRoutes.ProjectsItemOperations]: 'operations_20',
  [ConsoleRoutes.UserBilling]: 'billing_20',
  [ConsoleRoutes.UserSettings]: 'user_20',
  [ConsoleRoutes.UserSettingsApiKeys]: 'user_20',
  [ConsoleRoutes.UserSettingsAccount]: 'user_20',
  [ConsoleRoutes.ProjectsItemBranches]: 'branch_20',
  [ConsoleRoutes.ProjectsItemBranchesNew]: 'branch_20',
  [ConsoleRoutes.ProjectsItemBranchesItem]: 'branch_20',
  [ConsoleRoutes.ProjectsItemBranchesItemEndpointsNew]: 'endpoint_20',
  [ConsoleRoutes.ProjectsItemEndpoints]: 'endpoint_20',
  [ConsoleRoutes.ProjectsItemEndpointsNew]: 'endpoint_20',
  [ConsoleRoutes.ProjectsItemEndpointsItem]: 'endpoint_20',
  [ConsoleRoutes.ProjectsItemEndpointsItemEdit]: 'endpoint_20',
};

export const ANALYTICS_PAGE_MAPPER: Record<ConsoleRoutes, string> = {
  [ConsoleRoutes.Root]: 'root',
  [ConsoleRoutes.Home]: 'home',
  [ConsoleRoutes.ProjectsList]: 'projects_list',
  [ConsoleRoutes.ProjectsItem]: 'projects_item_dashboard',
  [ConsoleRoutes.ProjectsItemQuery]: 'projects_item_sql_editor',
  [ConsoleRoutes.ProjectsItemInsigts]: 'projects_item_insights',
  [ConsoleRoutes.ProjectsItemTables]: 'projects_item_tables',
  [ConsoleRoutes.ProjectsItemSettings]: 'projects_item_settings',
  [ConsoleRoutes.ProjectsItemSettingsGeneral]: 'projects_item_settings_general',
  [ConsoleRoutes.ProjectsItemSettingsOperations]: 'projects_item_settings_operations',
  [ConsoleRoutes.ProjectsItemSettingsDatabases]: 'projects_item_settings_databases',
  [ConsoleRoutes.ProjectsItemDatabases]: 'projects_item_settings_databases',
  [ConsoleRoutes.ProjectsItemRoles]: 'projects_item_settings_users',
  [ConsoleRoutes.ProjectsItemIntegrations]: 'projects_item_integrations',
  [ConsoleRoutes.ProjectsItemOperations]: 'projects_item_operations',
  [ConsoleRoutes.UserBilling]: 'billing',
  [ConsoleRoutes.UserSettings]: 'user_settings',
  [ConsoleRoutes.UserSettingsApiKeys]: 'user_settings_api_keys',
  [ConsoleRoutes.UserSettingsAccount]: 'user_settings_account',
  [ConsoleRoutes.ProjectsItemBranches]: 'projects_item_branches',
  [ConsoleRoutes.ProjectsItemBranchesNew]: 'projects_item_branches_new',
  [ConsoleRoutes.ProjectsItemBranchesItem]: 'projects_item_branches_item',
  [ConsoleRoutes.ProjectsItemBranchesItemEndpointsNew]: 'project_item_branches_item_endpoints_new',
  [ConsoleRoutes.ProjectsItemEndpoints]: 'projects_item_endpoints',
  [ConsoleRoutes.ProjectsItemEndpointsNew]: 'projects_item_endpoints_new',
  [ConsoleRoutes.ProjectsItemEndpointsItem]: 'projects_item_endpoints_item',
  [ConsoleRoutes.ProjectsItemEndpointsItemEdit]: 'projects_item_endpoints_item_edit',
};
